### PR TITLE
Replace StringValueTrait with From impls

### PR DESCRIPTION
**Pull request by djc**
This seems more idiomatic since it relies on well-known conversion
traits from the standard library. It is also more concise.

Also apply some other stylistic changes:

* Take &[T] instead of Vec<T> if the Vec cannot be reused
* Elide type annotations for collect() where unnecessary

### CODE REVIEW

**Comment by masalachai** [comment]
Hi @djc,

Thanks for this change. It's [failing the check for clippy], so could you fix that in your branch and re-push?

Also, the `StringValue` type was used at the time to get around quick-xml not having an easy way to serialize `String` to a tag with inner text, but they seem to [have added a way to do that recently] (https://github.com/tafia/quick-xml#unflattening-structs-into-verbose-xml). So we will mark that as a TODO for the future.

**Comment by djc** [comment]
Ah, missed the clippy failure. Fixed that up now.

I looked at the unflattening feature, but I'm not sure how that would work in the context of a `Vec<StringValue>`, for example like the one in `DomainList`?

**Comment by masalachai** [comment]
Hi @djc,

There are some tests also in se.rs and de.rs [that need to be updated](https://ci.masalachai.net/masalachai/epp-client/97) for this change from `Vec<&str>` to `&[&str]` and removal of the `StringValueTrait`

>how that would work in the context of a `Vec<StringValue>`

I haven't tried using the `$unflatten` yet but I thought it'd naturally serialize `Vec<String>` with `$unflatten` as a list of tags with inner text, but I will check and see if that is indeed the case.

**Comment by djc** [comment]
Fixed that up!

(With GitHub Actions, I usually get a notification if CI fails, so I know to go back and fix them rather than waiting for a maintainer to point it out. Looks like your Drone integration does not do that yet? Would be nice to have.)

**Comment by masalachai** [comment]
Thanks for the fix.

> Looks like your Drone integration does not do that yet? Would be nice to have.

I'll try to add it soon.

**Comment by masalachai** [comment]
Hi @djc and @nrempel 

> I usually get a notification if CI fails, so I know to go back and fix them rather than waiting for a maintainer to point it out. Looks like your Drone integration does not do that yet? Would be nice to have.

I have added email notifications for failing CI builds, if you could send me your email addresses where you would like to receive these notifications, I will add them to the recipient list. Thanks.

**Pull request merged**
