### PR TITLE
Move (de)serialization into EppObject methods

### PR DESCRIPTION
**Pull request by djc**
Since we always (de)serialize through an EppObject, there is no point
in maintaining a separate trait with a single impl.

As an additional advantage, by splitting the trait bounds for serialize vs deserialize we don't need to provide both. Since we usually only serialize command types and only deserialize response types, this is a useful simplification.

### CODE REVIEW

**Review by nrempel — COMMENTED** [review]
I like this change. Clippy has a recommendation to impl FromStr—would you say an idiomatic approach would be to implement FromStr and Display instead of methods from_str and to_str?

**Comment by djc** [comment]
I think FromStr makes sense. For Display, not as much; I think it implies semantics that don't really make sense here. Do you think we should use a different method name to avoid confusion?

**Comment by nrempel** [comment]
> I think FromStr makes sense. For Display, not as much; I think it implies semantics that don't really make sense here. Do you think we should use a different method name to avoid confusion?

FromStr provides from_str available right? Does Display provide to_string? I agree the semantics are a bit off, but it still provides what we need and in addition, implementing debug logs in the future would be easier as well.

**Comment by djc** [comment]
For debug logs I don't think you'll want the full XML, the derived `Debug` impls are likely to be perfect for that.

So actually `to_string()` is defined in [`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) which probably has a blanket implementation for `T: fmt::Display`. However, `ToString::to_string()` is infallible, whereas serde serialization is not, so I think that's a good reason to not use a trait here. I'm open to ideas on an alternative method name, though I think `to_string()` is likely to be just fine.

**Review by nrempel — APPROVED** [review]
Sounds good to me. This is a great change, the types look much simpler.

**Comment by djc** [comment]
If we decide to go with #50 this can just change the default implementations on the `EppXml` trait.

**Comment by djc** [comment]
After #50, this no longer makes sense.

**Pull request closed without merging**
