### PR TITLE
Track connection state

### PR DESCRIPTION
**Pull request by djc**
The external client/connection interface expects that to complete
full request/response cycles. However, at await points the stack
could simply be dropped, meaning the connection is left in an
inconsistent state. One relatively likely scenario is that a
transaction might be dropped while waiting for a response from the
server. For example, this might happen if the connection was
initiated by a HTTP request which was canceled/aborted.

There are different failure modes which can result from similar
scenarios depending on during what await point the future was
dropped. Since it's relatively difficult to protect against
these scenarios and some of them might manifest in indirect ways
(for example, a deserialization error might happen because the
incoming response was for a different kind of request), this PR
takes the approach of tracking in the connection whether we're
(supposedly) at a point where the connection is ready to send
another request. If transact() is called while the connection is
not in such a state, the connection will transparently attempt
to reconnect to clean up any erroneous state.

### CODE REVIEW

**Comment by djc** [comment]
Hi @masalachai, I'm not seeing CI kick off, do you know what might be up with that?

**Comment by djc** [comment]
Thanks for fixing it up! Are you sure you don't want to migrate to GitHub Actions? 😜

**Review by nrempel — COMMENTED** [review]
Very nice! I think this is almost certainly the issue encountered.

This is an elegant solution but I think if we could avoid reconnecting it would be even better. As an alternative approach do you think it would be possible to keep some atomic counter to keep track of how many requests never pulled the response off the connection? Then we could pop messages and discard them n - 1 times until we read the correct message?

**Comment by djc** [comment]
That only accounts for the case where we canceled after sending the request before receiving the response, so we'd have to do more complex state tracking. Do you want to make an attempt at doing that?

**Comment by nrempel** [comment]
Can you give an example of another error case? I can't think of another scenario we need to deal with.

**Comment by djc** [comment]
For example, the future might be dropped while we were in the middle of transferring the request or part way through the process of reading out the response. In the send case, we'd have to track what data is still left to send; in the receive case we'd have to track the data we've received. It's definitely feasible but still a good bit more complexity than this solution.

**Comment by nrempel** [comment]
Ah yeah, that's a good point. I didn't think about the future being dropped during mid-coroutine. In that case, I think we should merge this as it is an improvement and we can be smarter about how we handle these error states in the future.

**Review by nrempel — APPROVED** [review]

**Pull request merged**
