### PR TITLE
Update response <dcp> models

### PR DESCRIPTION
**Pull request by nrempel**
This pull request updates the `<dcp>` object representation in the greeting response to match [the RFC](https://datatracker.ietf.org/doc/html/rfc5730).

For `absolute` and `relative` expiry types, I have set these fields to the `StringValue` type for now. It appears that there is [some custom serialization logic](https://github.com/nrempel/epp-client/blob/c5fc82491b1b2ae3221045ce391a22c2ecf95ad9/epp-client/src/epp/request/domain/rgp/report.rs#L81) to handle other dates already. I think it would be good to update all of these dates and durations to use a [custom Serde data format](https://serde.rs/data-format.html). I'm not aware of any crate that can handle the expected format for [date/time](https://www.w3.org/TR/xmlschema-2/#isoformats) and [duration](https://www.w3.org/TR/xmlschema-2/#duration).

Do you think this would work best as a separate issue and pull request?

### CODE REVIEW

**Comment by masalachai** [comment]
> I think it would be good to update all of these dates and durations to use a [custom Serde data format](https://serde.rs/data-format.html). I'm not aware of any crate that can handle the expected format for [date/time](https://www.w3.org/TR/xmlschema-2/#isoformats) and [duration](https://www.w3.org/TR/xmlschema-2/#duration).

This would be a very good solution I think.

I wanted to have a date type (probably extend DateTime<Utc>) that cleanly ser/de to and from ISO8601 formats and didn't find one at the time. Since this is a general enough requirement (type serialization to and from ISO8601 formats) do you think this should be its own crate in the long term? For now I think it's good to have it in this repo.

**Comment by nrempel** [comment]
Sounds good. For DateTime and Duration, it might make sense to contribute back to quick-xml because they are part of the [XML spec](https://www.w3.org/TR/xmlschema-2/). I'm not sure if they would consider (de)serializers like that in scope for the project but we could see.

As for phone numbers and country codes, that probably makes sense to keep as part of this library.

**Comment by masalachai** [comment]
Ok, thanks for checking with the quick-xml project and for the changes in this PR. I will merge it soon.

**Comment by djc** [comment]
Having written some serde data format implementations, I don't think that abstraction fits very well. The most attractive solution might be to implement some more alternative serializers/deserializers (that is, a module containing `serialize` and `deserialize` functions) in chrono, which already collects these [here](https://docs.rs/chrono/0.4.19/chrono/serde/index.html). However, given that chrono is not very actively maintained currently, this direction will probably not make a lot of sense.

Given that these are just modules with functions in them, it doesn't really matter where these live, so it'd probably make sense to implement them in this crate until/unless there's a response in https://github.com/tafia/quick-xml/issues/339 which would probably make more sense.

**Comment by nrempel** [comment]
@djc which abstraction are you referring to? The general approach of splitting the de/serializers into a separate crate?

**Comment by djc** [comment]
The abstraction of a "custom Serde data format". A serde data format, at least as referred to on the page you linked to, means a `Serializer` and/or `Deserializer` implementation (for something like JSON, CBOR, etc).

**Comment by nrempel** [comment]
Ah, ok. Yeah that makes sense. The serde model/architecture still confuses me sometimes.

**Pull request merged**
