### PR TITLE
Take Login ext_uris values as a slice to allow caller to avoid allocation

### PR DESCRIPTION
**Pull request by djc**
In some cases the caller might be able to use a const slice for this.

### CODE REVIEW

**Comment by masalachai** [comment]
Hi @djc, the clippy check for this PR is [failing](https://ci.masalachai.net/masalachai/epp-client/314/1/4).

**Comment by djc** [comment]
Oops, thanks for the notification! Will pick it up as soon as possible.

We're pretty close to putting this in production, how would you feel about adding one or both of us as collaborators to the repo so you don't have to be on the hook for every review?

**Comment by djc** [comment]
Fixed it up!

**Review by nrempel — APPROVED** [review]
👍🏼

**Comment by masalachai** [comment]
>how would you feel about adding one or both of us as collaborators to the repo so you don't have to be on the hook for every review?

Sure, I'll add both of your accounts later today.

**Comment by djc** [comment]
> Sure, I'll add both of your accounts later today.

Thanks! Maybe not necessary to say this, but if at any time you feel like we merged something you have concerns with, please don't hesitate to open an issue/comment on the PR.

**Comment by masalachai** [comment]
>please don't hesitate to open an issue/comment on the PR

Sure, thanks. I will be watching the repo so will do that if I have anything to comment upon.

**Pull request merged**
