### PR TITLE
Small logging improvements

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by nrempel** [comment]
Is it worth considering https://github.com/tokio-rs/tracing here?

**Comment by djc** [comment]
I think that would be an improvement, yes. @masalachai what do you think? I think tracing is generally seen as somewhat of a successor to log. It has interoperability with the log crate but also includes a bunch of other functionality (including structured logging).

**Comment by masalachai** [comment]
The tracing crate looks good. I'm ok with moving to using that instead of log. Thanks for the suggestion.

**Comment by djc** [comment]
Added a commit that switches to tracing.

**Review by nrempel — APPROVED** [review]

**Pull request merged**
